Repository pods-framework/pods-gravity-forms, pull requests merged in 2018-04, with the labels that each got.

#109 Add backwards-compatible update for GF 2.3. Fix #108
  includes/Pods_GF.php
  includes/Pods_GF_UI.php
  includes/functions.php
Labels: bug

#100 Allow feeds to be duplicated, support multiple array value checking
  includes/Pods_GF.php
  includes/Pods_GF_Addon.php
Labels: enhancement

#91 add GitHub Plugin URI: for afragen updater
  pods-gravity-forms.php
Labels: in progress
